# Generated by Django 2.0.13 on 2019-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('last_update', models.DateField(auto_now=True)),
                ('publisher', models.CharField(max_length=254)),
                ('contactPoint', models.CharField(max_length=254)),
                ('mbox', models.EmailField(max_length=254)),
                ('identifier', models.CharField(max_length=254)),
                ('accessLevel', models.CharField(choices=[('public', 'Open&Free = is or could be made publicly available to all without restrictions'), ('restricted-public', 'Available, with some rules = available under certain use restrictions'), ('non-public', 'Private  = not available to members of the public')], default='public', max_length=10)),
                ('landingPage', models.URLField()),
                ('language', models.CharField(max_length=254)),
                ('issued', models.DateField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name_plural': 'research',
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
