# Generated by Django 2.0.13 on 2019-07-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190720_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'Français'), ('Italian', 'Italiano'), ('Spanish', 'Español')], default='English', max_length=30),
        ),
    ]
