# Generated by Django 2.0.13 on 2019-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20190726_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='times_seen',
            field=models.IntegerField(default=0),
        ),
    ]
